---
- hosts: '{{target}}'
  gather_facts: no

  tasks:
    - name: Copy profile yaml to server
      ansible.builtin.copy:
        src: "{{root_folder}}/lxd/servers/jenkins-node1/jenkins-node1-profile.yml"
        dest: /tmp/

    - name: Copy script for server creation
      ansible.builtin.copy:
        src: "{{root_folder}}/lxd/servers/jenkins-node1/create-server.sh"
        dest: /tmp/create-server.sh

    - name: Execute script for container creation
      ansible.builtin.command: bash /tmp/create-server.sh

    - name: Delete profiles files
      file:
        state: absent
        path: "/tmp/jenkins-node1-profile.yml"

    - name: Delete script 
      file:
        state: absent
        path: "/tmp/create-server.sh"