---

- hosts: 'captain'
  #remote_user: '{{user}}'
  gather_facts: no

  tasks:
    - name: Creates Plex volume
      become: true
      file:
        path: /hdd-pool/appdata/plex
        state: directory
        owner: '{{user}}'
        group: '{{user}}'
        mode: 0700
        recurse: yes
      
    - name: Create Plex container
      docker_container:
        name: plex
        image: plexinc/pms-docker
        state: started
        pull: yes
        restart_policy: unless-stopped
        container_default_behavior: no_defaults
        network_mode: bridge
        networks:
          - name: "macvlan24"
            ipv4_address: "192.168.50.5"
        ports:
          - "2456-2457:2456-2457/udp"
          - "32400:32400/tcp"
          - "3005:3005/tcp"
          - "8324:8324/tcp"
          - "32469:32469/tcp"
          - "1900:1900/udp"
          - "32410:32410/udp"
          - "32412:32412/udp"
          - "32413:32413/udp"
          - "32414:32414/udp"
        volumes:
          - /hdd-pool/appdata/plex/config/:/config/
          - /hdd-pool/appdata/plex/transcode/:/transcode/
          - /hdd-pool/media/:/media/
        env:
          TZ: "America/Toronto"
          ADVERTISE_IP: "http://192.168.50.5:32400/"
          
