---
- hosts: '{{target}}'
  remote_user: '{{user}}'
  become: true
  gather_facts: no

  tasks:

    - name: Apply new network configs
      ansible.builtin.command:
        cmd: netplan apply

    - name: Install Virt packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'qemu-kvm', 'libvirt-daemon-system', 'libvirt-clients', 'bridge-utils', 'virtinst', 'cloud-init', 'cloud-image-utils', 'lxc', 'lxd', 'zfsutils-linux']

    - name: Clean apt cache
      command:
        cmd: apt-get clean

    - name: Ensure group "libvirt", "lxd" and "kvm"
      ansible.builtin.group:
        name:  '{{ item }}'
        state: present
      loop: ['libvirt', 'kvm', 'lxd']

    - name: adding existing user '{{ user }}' to group libvirt and kvm
      user:
        name: '{{ user }}'
        groups: '{{ item }}'
        append: yes
      loop: ['libvirt', 'kvm', 'lxd']

    - name: Start and enable virtuallization services
      ansible.builtin.service:
        name: '{{ item }}'
        state: started
        enabled: yes
      loop: 
        - libvirtd
        - cloud-init-local.service
        - cloud-init.service
        - cloud-config.service
        - cloud-final.service