pipeline {
    agent any

    stages{
  
        stage('Build Docs') {

            steps {
                sh 'docker build  -f docs-config/Dockerfile -t ghcr.io/gabrielpsilva/homelab-docs .'
            }
        }

        stage('Push image') {
            docker.withRegistry('https://registry.hub.docker.com', 'gabrielpsilva-gh90') {                   
                app.push("${env.BUILD_NUMBER}")            
                app.push("latest")        
            }    
        }   
    }
}
