pipeline {
    agent any

    environment {
        registry = "ghcr.io/gabrielpsilva/homelab"
    }
    
    stages{

        stage('Build Docs') {

            steps {
                sh 'docker build -f docs-config/Dockerfile -t ghcr.io/gabrielpsilva/homelab-docs .'
            }
        }

        stage('Push image') {
            steps{

                withCredentials([usernamePassword(credentialsId: 'gab-90d', passwordVariable: 'ghuserpass', usernameVariable: 'ghuser')]) {
                    sh "docker login -u ${ghuser} -p ${ghuserpass} 'https://${registry}'"
                }

                sh "docker push ${registry}"
            }
        }
    }
}
