---
- hosts: '{{target}}'
  gather_facts: no

  tasks:

    - name: Copy profile yaml to server
      ansible.builtin.copy:
        src: "{{root_folder}}/servers/jenkins" 
        dest: /tmp/

    - name: "Create jenkins master container"
      command: "{{ item }}"
      loop:
        - lxc profile create jenkins-master
        - bash -c "cat /tmp/jenkins/profiles/jenkins-master-profile.yml | lxc profile edit jenkins-master"
        - lxc launch -p conf-autostart-on.yml -p disk-std.yml -p network-lvl1.yml -p jenkins-master images:ubuntu/focal/cloud jenkins-master

    - name: "Create jenkins node1 container"
      command: "{{ item }}"
      loop:
        - lxc profile create jenkins-node1
        - bash -c "cat /tmp/jenkins/profiles/jenkins-node1-profile.yml | lxc profile edit jenkins-node1"
        - lxc launch -p conf-autostart-on.yml -p disk-std.yml -p network-lvl1.yml -p jenkins-node1 images:ubuntu/focal/cloud jenkins-node1

    - name: Delete script 
      file:
        state: absent
        path: "/tmp/jenkins"
        