---
- hosts: '{{target}}'
  remote_user: '{{user}}'
  become: true


  tasks:

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes


    - name: Install Utils
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'vim', 'git', 'curl', 'rsync', 'whois', 'cron']

    - name: Clean apt cache
      command:
        cmd: apt-get clean




@reboot java -jar agent.jar -jnlpUrl 'http://192.168.50.10:8080/computer/node1/jenkins-agent.jnlp' -secret @/home/jenkins/jk-secret-file -workDir /home/jenkins/jenkins-workspaces

~                                                                                                                                                                                                                                                                           
~ 