---
- hosts: '{{target}}'
  become: true



  tasks:
    - name: backup /etc/netplan/00-installer-config.yaml
      ansible.builtin.copy:
        src: /etc/netplan/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml.bkp
        remote_src: yes
        backup: yes


    - name: Create br0 bridge interface
      copy:
        dest: "/etc/netplan/00-installer-config.yaml"
        content: |
          network:
            renderer: networkd
            ethernets:
              enp2s0:
                dhcp4: true
                optional: true
            version: 2

            bridges:
              br0:
                interfaces: [enp2s0]
                optional: true
                dhcp4: yes

    - name: Apply new network configs
      ansible.builtin.command:
        cmd: netplan apply

    - name: Install Virt packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'qemu-kvm', 'libvirt-daemon-system', 'libvirt-clients', 'bridge-utils', 'virtinst', 'cloud-init', 'cloud-image-utils']

    - name: Clean apt cache
      command:
        cmd: apt-get clean

    - name: Ensure group "libvirt" and "kvm"
      ansible.builtin.group:
        name:  '{{ item }}'
        state: present
      loop: ['libvirt', 'kvm']

    - name: adding existing user '{{ user }}' to group libvirt and kvm
      user:
        name: '{{ user }}'
        groups: '{{ item }}'
        append: yes
      loop: ['libvirt', 'kvm']

    - name: Start and enable virtuallization services
      ansible.builtin.service:
        name: '{{ item }}'
        state: started
        enabled: yes
      loop: 
        - libvirtd
        - cloud-init-local.service
        - cloud-init.service
        - cloud-config.service
        - cloud-final.service